name: Build and Test
permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.20'

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build ./...

    - name: Run tests
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: go test ./...

    - name: Upload summary
      uses: actions/upload-artifact@v4
      with:
        name: test-summary
        path: ./test/summary.svg